# Generated by Django 5.2.17 on 2026-08-25 08:22

import django.core.validators
import django.db.models.deletion
import investors.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Key the website looks the section up by, e.g. "financial-highlight". Changing this will break the page until the site is updated to match.', max_length=80, unique=True)),
                ('name', models.CharField(help_text='Heading shown on the website.', max_length=160)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='investors.section')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('file', models.FileField(blank=True, help_text='The document itself. Leave empty only for a document hosted elsewhere.', upload_to=investors.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'xlsx', 'xls', 'doc', 'docx', 'zip'])])),
                ('external_url', models.URLField(blank=True, help_text='Legacy link, used only when no file is uploaded. Uploading a file takes precedence and is always preferred — an external host can disappear without warning.', max_length=800)),
                ('doc_date', models.DateField(blank=True, help_text="Date of the filing. Shown as e.g. 'Jun 2026' and used for sorting.", null=True)),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide from the website without deleting.')),
                ('is_unavailable', models.BooleanField(default=False, help_text='Listed on the website but not downloadable — the file was never recovered from the retired host. Upload a file to clear this.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers first; documents with the same number sort by date.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='investors.category')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', models.OrderBy(models.F('doc_date'), descending=True, nulls_last=True), '-created_at'],
                'indexes': [models.Index(fields=['category', 'is_published'], name='investors_d_categor_a70653_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('section', 'name'), name='unique_category_name_per_section'),
        ),
    ]
