# Generated by Django 5.2.17 on 2026-08-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('talk', 'Talk to AeonX'), ('enquiry', 'Project enquiry')], max_length=10)),
                ('company_name', models.CharField(max_length=300)),
                ('full_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('country_code', models.CharField(blank=True, max_length=20)),
                ('phone_number', models.CharField(max_length=40)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('additional_information', models.TextField(blank=True)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('type_of_engagement', models.CharField(blank=True, max_length=200)),
                ('timeline', models.CharField(blank=True, max_length=100)),
                ('brief_description', models.TextField(blank=True)),
                ('is_handled', models.BooleanField(default=False, help_text='Tick once someone has followed up.')),
                ('notify_email_sent', models.BooleanField(default=False, editable=False, help_text='Whether the sales-team notification email went out.')),
                ('source_page', models.CharField(blank=True, max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_handled', '-created_at'], name='contacts_co_is_hand_32d969_idx')],
            },
        ),
    ]
