# Generated by Django 5.2.17 on 2026-08-25 10:21

import blog.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('slug', models.SlugField(max_length=250)),
                ('author', models.CharField(default='admin', max_length=120)),
                ('published_at', models.DateField(default=django.utils.timezone.now)),
                ('path', models.CharField(help_text="The page's URL path. Changing it breaks every existing link to this post, including search results.", max_length=500, unique=True)),
                ('cover', models.ImageField(blank=True, upload_to=blog.models.cover_upload_path)),
                ('cover_external', models.URLField(blank=True, help_text='Legacy image URL, used only if no cover file is uploaded.', max_length=800)),
                ('body_html', models.TextField(blank=True)),
                ('excerpt', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.category')),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BodyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=blog.models.body_image_upload_path)),
                ('original_url', models.URLField(blank=True, help_text='Where it was fetched from, when migrated off the old host.', max_length=800)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_images', to='blog.post')),
            ],
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_published', '-published_at'], name='blog_post_is_publ_9ad937_idx'),
        ),
    ]
