# Generated by Django 5.2.17 on 2026-08-27 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Shown across the top of every page. Keep it short — it is one line on desktop and wraps badly past roughly 120 characters.', max_length=200)),
                ('url', models.CharField(blank=True, help_text='Where the bar links to. Leave empty and the bar is not clickable (it renders as plain text rather than a link that goes nowhere).', max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text='Unticked hides the bar on every page. The strip disappears entirely rather than showing an empty band.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'announcement bar',
                'verbose_name_plural': 'announcement bar',
            },
        ),
    ]
