// CloudFront Function (cloudfront-js-2.0), viewer request, default behaviour.
// Generated by _cfn.py from the build's redirect pages. Edit the template, not the output.
var HOST = 'aeonx.digital';
var REDIRECTS = {
  "/about-us/": "/who-we-are/foundation/",
  "/author/admin/": "/insights/blog/",
  "/author/chandni-gadhvi/": "/insights/blog/",
  "/author/": "/insights/blog/",
  "/author/rajat-jindal/": "/insights/blog/",
  "/career/": "/who-we-are/career/",
  "/case-studies/": "/insights/",
  "/category/aws/": "/insights/blog/",
  "/category/cloud-computing/": "/insights/blog/",
  "/category/digital-transformation/": "/insights/blog/",
  "/category/": "/insights/blog/",
  "/category/sap/": "/insights/blog/",
  "/category/success-stories-aws/": "/insights/",
  "/category/success-stories-sap/": "/insights/",
  "/category/uncategorized/": "/insights/blog/",
  "/code-and-policy/": "/investor-relations/",
  "/cookies/": "/cookie-policy/",
  "/corporate-governance/": "/investor-relations/",
  "/dipl-testimonial/": "/who-we-are/culture/",
  "/financial-highlight/": "/investor-relations/",
  "/industries/energy-oil-gas/": "/industries/energy-fertiliser-oil-gas/",
  "/industries/": "/industries/manufacturing/",
  "/industries/textiles/": "/industries/textiles-apparel/",
  "/investor-contact/": "/contact-us/",
  "/investor/": "/investor-relations/",
  "/investors/": "/investor-relations/",
  "/newsroom/aeonx-aws-partner-network/": "/2022/06/08/aeonx-aws-partner-network/05/48/43/918/aws/admin/",
  "/newsroom/": "/insights/blog/",
  "/other-documents/": "/investor-relations/",
  "/privacy/": "/privacy-policy/",
  "/resources/blog/": "/insights/blog/",
  "/resources/": "/insights/",
  "/resources/success-stories/aws-tabs/": "/insights/",
  "/resources/success-stories/": "/insights/",
  "/resources/success-stories/sap-tabs/": "/insights/",
  "/shareholder-information/": "/investor-relations/shareholding-pattern/",
  "/solutions/business-solution/": "/products/",
  "/solutions/cloud-solution/": "/services/",
  "/solutions/": "/products/",
  "/terms/": "/terms-and-conditions/",
  "/termsonlinepayment/": "/terms-and-conditions/",
  "/testimonials/": "/who-we-are/culture/",
  "/thank-you/": "/contact-us/",
  "/what-we-do/": "/services/",
  "/who-we-are/": "/who-we-are/foundation/"
};
// Posts whose category changed from "uncategorized" to "aws" after import.
var MOVED_POST_IDS = {"243266": 1, "243267": 1, "243269": 1, "243270": 1, "243271": 1, "243274": 1, "243275": 1};
// Paths served by other origins. Never rewritten here, even if the function is
// attached more widely than intended.
var PASS = /^\/(api|manage|admin|static)\//;

function query(req) {
  var parts = [];
  for (var name in req.querystring) {
    var q = req.querystring[name];
    var values = q.multiValue ? q.multiValue.map(function (v) { return v.value; }) : [q.value];
    values.forEach(function (v) {
      parts.push(v === '' ? name : name + '=' + v);
    });
  }
  return parts.length ? '?' + parts.join('&') : '';
}

function moved(location) {
  return {
    statusCode: 301,
    statusDescription: 'Moved Permanently',
    headers: {
      location: { value: location },
      'cache-control': { value: 'public, max-age=86400' }
    }
  };
}

function handler(event) {
  var req = event.request;
  var host = req.headers.host ? req.headers.host.value.toLowerCase() : HOST;
  var uri = req.uri;

  if (host === 'www.' + HOST) {
    return moved('https://' + HOST + uri + query(req));
  }
  if (PASS.test(uri)) {
    return req;
  }

  var key = uri.charAt(uri.length - 1) === '/' ? uri : uri + '/';
  if (Object.prototype.hasOwnProperty.call(REDIRECTS, key)) {
    return moved('https://' + HOST + REDIRECTS[key] + query(req));
  }
  var m = key.match(/^(\/\d{4}\/.*\/)(\d+)\/uncategorized\/(.*)$/);
  if (m && MOVED_POST_IDS[m[2]]) {
    return moved('https://' + HOST + m[1] + m[2] + '/aws/' + m[3] + query(req));
  }

  if (uri.charAt(uri.length - 1) === '/') {
    req.uri = uri + 'index.html';
  } else if (uri.split('/').pop().indexOf('.') === -1) {
    req.uri = uri + '/index.html';
  }
  return req;
}
